### PR TITLE
A massive cleanup of all the files in this repository

### PR DESCRIPTION
**Pull request by aaronfranke**
I don't know how, but the files currently in this repository are filled with tons of garbage. Some of the HTML files have thousands of empty lines with random indentation. 

This PR is a massive cleanup of this repository's files, including removing trailing whitespace, removing extraneous empty lines, cleaning SVG files, ensuring files comply with POSIX standards, and also formatting everything using VS Code's default formatting tools. I'm not sure what your style preferences are, but this PR is undoubtedly a massive improvement.

### CODE REVIEW

**Comment by cbscribe** [comment]
Thing is, the html files are all autogenerated by hugo, so any changes will be blown away next time the content is updated.

And the theme files are from the source repository.

**Comment by aaronfranke** [comment]
Why do they generate with thousands of empty lines with random indentation?

Feel free to pick out whatever you like from this PR, I'm not familiar with this repository but I'm just trying to help out where I can.

**Comment by cbscribe** [comment]
I'm not sure, but It's not supposed to be human readable anyway. There is a `minify` flag, so I'll take a look at what that generates.

**Comment by aaronfranke** [comment]
@cbscribe I re-ran the formatting on master, feel free to re-review and use as you wish.

**Comment by cbscribe** [comment]
Thanks, but I'm not going to change third party css, etc. It's just going to get overwritten any time it's updated from upstream. Maybe you could try contributing at https://github.com/gohugoio/hugo

**Pull request closed without merging**
